name: CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # analyse-projects-code:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install dependencies and run linters
  #       run: pip install flake8

  #     - run: flake8 ./server

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - run: npm install eslint
  #     - run: npm run lint
      
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Containers with Secrets
        env:
          # This maps your GitHub Secrets to shell variables
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          # Create root env file for Docker Compose
          echo "DB_PASS=$DB_PASS" > .env
          echo "DB_USER=$DB_USER" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
      
          # Create frontend config file for Vite
          echo "VITE_API_URL=$API_URL" > ./client/.env

      - name: build images
        run: docker compose build
      
      - name: start containers and test
        run: docker compose up

      - name: debug containers
        if: failure()
        run: docker compose logs db

      - name: test URL
        run: |
          docker compose ps
          curl -f http://localhost:3000 || exit 1